export const GENTELELLA_RUNTIME_MODULES = {
    calendar: 'gentelella/v4/calendar',
    charts: 'gentelella/v4/charts',
    'command-palette': 'gentelella/v4/command-palette',
    'data-adapter': 'gentelella/v4/data-adapter',
    details: 'gentelella/v4/details',
    'file-manager': 'gentelella/v4/file-manager',
    'form-controls': 'gentelella/v4/form-controls',
    inbox: 'gentelella/v4/inbox',
    kanban: 'gentelella/v4/kanban',
    markup: 'gentelella/v4/markup',
    menus: 'gentelella/v4/menus',
    modal: 'gentelella/v4/modal',
    'page-actions': 'gentelella/v4/page-actions',
    'product-images': 'gentelella/v4/product-images',
    'product-mockups': 'gentelella/v4/product-mockups',
    settings: 'gentelella/v4/settings',
    shell: 'gentelella/v4/shell',
    'shell-render': 'gentelella/v4/shell-render',
    tables: 'gentelella/v4/tables',
    toast: 'gentelella/v4/toast',
} as const
