packages:
  - "auth-service"
  - "capability-system"
  - "canvas-engine"
  - "canvas-components"
  - "canvas-components-lixpi-specific"
  - "constants/ts"
  - "debug-tools/ts"
  - "dynamodb-service"
  - "nats-auth-callout-service"
  - "nats-service/ts"
  - "prosemirror"
  - "test-utils"
  - "ui-kit"
  - "ui-primitives"
  - "usage-reporter"
